  // All available themes (30 total)
  export const allThemes = [
    { name: "warm", emoji: "🔥", desc: "Warm" },
    { name: "cool", emoji: "❄️", desc: "Cool" },
    { name: "neutral", emoji: "⚪", desc: "Neutral" },
    { name: "vibrant", emoji: "🌈", desc: "Vibrant" },
    { name: "pastel", emoji: "🌸", desc: "Pastel" },
    { name: "monochrome", emoji: "⚫", desc: "Monochrome" },
    { name: "sunset", emoji: "🌅", desc: "Sunset" },
    { name: "midnight", emoji: "🌙", desc: "Midnight" },
    { name: "trees", emoji: "🌲", desc: "Trees" },
    { name: "desert", emoji: "🏜️", desc: "Desert" },
    { name: "aurora", emoji: "🌌", desc: "Aurora" },
    { name: "neon", emoji: "💫", desc: "Neon" },
    { name: "spring", emoji: "🌱", desc: "Spring" },
    { name: "summer", emoji: "☀️", desc: "Summer" },
    { name: "autumn", emoji: "🍂", desc: "Autumn" },
    { name: "winter", emoji: "❄️", desc: "Winter" },
    { name: "cosmic", emoji: "🌠", desc: "Cosmic" },
    { name: "galaxy", emoji: "🌌", desc: "Galaxy" },
    { name: "ocean", emoji: "🌊", desc: "Ocean" },
    { name: "mountain", emoji: "⛰️", desc: "Mountain" },
    { name: "city", emoji: "🏙️", desc: "City" },
    { name: "vintage", emoji: "📷", desc: "Vintage" },
    { name: "retro", emoji: "🎮", desc: "Retro" },
    { name: "cyberpunk", emoji: "🤖", desc: "Cyberpunk" },
    { name: "steampunk", emoji: "⚙️", desc: "Steampunk" },
    { name: "minimalist", emoji: "⬜", desc: "Minimalist" },
    { name: "luxury", emoji: "💎", desc: "Luxury" },
    { name: "rustic", emoji: "🪵", desc: "Rustic" },
    { name: "tropical", emoji: "🌴", desc: "Tropical" },
    { name: "arctic", emoji: "🧊", desc: "Arctic" },
    { name: "sahara", emoji: "🏜️", desc: "Sahara" },
    { name: "forest", emoji: "🌳", desc: "Forest" },
    { name: "cafe", emoji: "☕", desc: "Cafe" },
  ];